name: Telegram Notification

on:
  repository_dispatch: # triggered by external API call

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      SHARE_KEY: ${{ github.event.client_payload.key }}
      USER_ID: ${{ github.event.client_payload.userId }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Send Telegram Notification
        run: node sendKey.js
